version: 2

sources:
  - name: linkedin_job_posting
    database: big-star-collectibles-433202
    schema: raw_data
    tables:
      - name: raw_linkedin_job_posting
        description: "Raw data from the LinkedIn job postings dataset extracted from Airbyte"
  - name: transformed_job_posting_data
    database: big-star-collectibles-433202
    schema: transformed_data
    tables:
      - name: int_job_posting
        description: "Summary of job postings by location"
     # - name: stg_linkedin_jobs_postings
      #  description: "Staging table for LinkedIn jobs postings data"
